include /home/koofte/.config/kitty/themes/one-dark.conf
include ~/.config/kitty/opts/style.conf
include ~/.config/kitty/opts/shell.conf
include ~/.config/kitty/opts/font.conf
include ~/.config/kitty/opts/core.conf
