alias ff="fastfetch"
alias un="echo ekmek"
alias joke='curl -s https://v2.jokeapi.dev/joke/Programming | jq -r ".setup + \" \" + .delivery"'
alias alice='llama-server -m ~/aimodels/alice.llama.31.8.guff -t 8'
alias cat="bat -p --pager never"
alias catp="bat --pager never"
alias _cat="command cat"
alias pr="cd ~/projects"
alias pa="cd ~/projects/__active__"
alias y="yazi"
alias nsfw="~/projects/cat/ii.sh"
alias ...='../..'
alias ....='../../..'
alias f='find . -type f -name'
alias fa='find . -name'
alias n='nvim'
alias hp='hyprpm'
alias sd='sudo'
alias pi='sudo pacman -Sy --needed'
alias pu='sudo pacman -Syu --needed'
alias rs='sudo -k'
alias rdm="ls README.md | entr -r sh -c 'clear && mdcat README.md'"
alias ls="eza --icons --git"
alias ll="eza --icons --git -lah"
alias lg="eza --icons --git -lah --no-permissions --no-filesize --no-user --no-time"
alias _ls="command ls"
alias what="echo the fuck"
alias WHAT="echo THE FUCK"
alias clear="printf '\033[2J\033[3J\033[1;1H'"
alias _clear="command clear"
