alias ff="fastfetch"
alias un="echo ekmek"
alias joke='curl -s https://v2.jokeapi.dev/joke/Programming | jq -r ".setup + \" \" + .delivery"'
#alias alice='llama-server -m ~/aimodels/alice.llama.31.8.guff -t 8' obsolute
alias cat="bat -p --pager never"
alias catp="bat --pager never"
alias _cat="command cat"
alias pr="cd ~/projects"
alias pa="cd ~/projects/__active__"
alias pad="cd ~/projects/dynarch"
alias dcr="cd ~/projects/dynarch/dynarch-compiler-rs"
alias y="yazi"
alias nsfw="~/projects/cat/ii.sh"
alias ..="cd .."
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias f='find . -type f -name'
alias fa='find . -name'
alias n='nvim'
alias ncc='cd ~/.config/nvim; nvim'
alias hp='hyprpm'
alias pi='sudo pacman -Sy --needed'
alias pu='sudo pacman -Syu --needed'
alias rsudo='sudo -k'
alias rdm="ls README.md | entr -r sh -c 'clear && mdcat README.md'"
alias ls="eza --icons --git"
alias ll="eza --icons --git -lah"
alias lg="eza --icons --git -lah --no-permissions --no-filesize --no-user --no-time"
alias _ls="command ls"
alias what="echo the fuck"
alias WHAT="echo THE FUCK"
alias clear="printf '\033[2J\033[3J\033[1;1H'"
alias _clear="command clear"
alias wcc="warp-cli connect"
alias wcd="warp-cli disconnect"
alias wcs="warp-cli status"
alias wcm="warp-cli mode"
alias sz="source ~/.zshrc"
alias zc="cd ~/zsh-sources; nvim"
alias zr="nvim ~/.zshrc"
alias kft="~/scripts/env_mng/kft_env.sh"
alias kset="~/scripts/env_mng/kft_env.sh set"
alias bestlook="echo 1769212211"
alias mkdir="mkdir -pv"
alias _kkdir="command mkdir"
alias mk="make -j$(nproc)"
alias mkc="make clean && -j$(nproc)"
alias gdb="gdb -tui"
alias rmophan='pacman -Qdtq | fzf -m --prompt="Remove orphan: " --marker="✔ " | xargs -r sudo pacman -Rns'
