preload = /home/koofte/.wallpapers/ngnl2.jpg
wallpaper = HDMI-A-1,/home/koofte/.wallpapers/ngnl2.jpg
wallpaper = DP-1,/home/koofte/.wallpapers/ngnl2.jpg
wallpaper = HDMI-A-2,/home/koofte/.wallpapers/ngnl2.jpg
