disable_ligatures no
enable_audio_bell no

url_style curly

remember_window_size no
window_padding_width 10

background_opacity 0.6
scrollbar_hadnle_opacity 0
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 0
