# color - ado 1
foreground #FBF7F8
background #2A2B44
cursor     #FBF7F8

color0  #2A2B44
color1  #B6B9D6
color2  #7E8BB1
color3  #E9E6EB
color4  #A3A6C6
color5  #B6B9D6
color6  #7E8BB1
color7  #E0DCE2

color8  #3A3D5C
color9  #C7CAE3
color10 #8F9BC0
color11 #FBF7F8
color12 #B0B3D0
color13 #C7CAE3
color14 #8F9BC0
color15 #FBF7F8

selection_foreground #2A2B44
selection_background #C7CAE3
