# color - onecolor
foreground #fff2d8
# background #0b1a24
background #282c34
cursor     #1fd1c7

color0  #3a4a57
color1  #ff636e
color2  #7dffb3
color3  #ffe66d
color4  #4aa3ff
color5  #c85cff
color6  #42d6d6
color7  #bfe6e0
color8  #6b8a94
color9  #ff636e
color10 #7dffb3
color11 #ffe66d
color12 #4aa3ff
color13 #c85cff
color14 #42d6d6
color15 #fff2d8
 
selection_foreground #0b1a24
selection_background #1fd1c7
